CREATE TABLE EMPLOYEE (
   EMPLOYEE_ID SERIAL PRIMARY KEY,
   NAME VARCHAR(50) NOT NULL,
   POSITION VARCHAR(50),
   DEPARTMENT VARCHAR(50),
   HIRE_DATE DATE,
   SALARY NUMERIC(10,2)
);

SELECT * FROM EMPLOYEE;

-- OPTIONAL QUERY IF YOU WANT TO DELETE THE ALL ROWS 
-- TRUNCATE TABLE EMPLOYEE ;
-- IT WILL DELETE ALL THE RECORDS BUT IT WIL NOT DELETE THE SERIAL USED COLUMN 
-- FOR THAT YOU HAVE TO WRITE THE QUERY 
-- TRUNCATE TABLE EMPLOYEE RESTART IDENTITY ;


-- IF YOU BY MISTAKELY NAMED YOUR COLUMN WRONG 
-- THEN USE 
-- ALTER TABLE EMPLOYEE 
-- RENAME COLUMN -- TO -- ;
-- IN THAT WAY IT WILL WORK.


-- LETS INSERT DATA IN THE TABLE 

INSERT INTO EMPLOYEE(NAME,POSITION,DEPARTMENT,HIRE_DATE,SALARY)
       VALUES
	   ('AJIT SHARMA','DATA ANALYST', 'DATA SCIENCE' ,'2022-05-15',65000.00),
	   ('PRIYA DESAI','SOFTWARE ENGINEER','IT','2021-09-20',75000.00),
	   ('RAJESH KUMAR','HR MANAGER','HR','2019-03-10',82000.00),
	   ('SNEHA PATEL','MARKETING SPECIALIST','MARKETING','2020-11-25',58000.00),
	   ('VIKRAM SINGH','SALES EXECUTIVE','SALES','2023-02-12',62000);


SELECT * FROM EMPLOYEE;

-- * HOW TO DELETE ROWS AND COLUMNS IN THE SQL

-- SPECIFIC ROW 

DELETE FROM EMPLOYEE 
WHERE EMPLOYEE_ID = 5;

-- AFTER DELETED I AGAIN ADDED THE ROW 

INSERT INTO EMPLOYEE (NAME,POSITION,DEPARTMENT,HIRE_DATE,SALARY)
            VALUES
			('VIKRAM SINGH','SALES EXECUTIVE','SALES','2023-02-12',62000);


-- NOW HOW TO DELETE SPECIFIC COLUMN 

ALTER TABLE EMPLOYEE
DROP COLUMN SALARY;


SELECT * FROM EMPLOYEE;

-- LETS GET OUR SALARY COLUMN BACK 

ALTER TABLE EMPLOYEE 
ADD COLUMN SALARY NUMERIC(10,2);

UPDATE EMPLOYEE
SET SALARY = 65000.00
WHERE EMPLOYEE_ID = 1;

UPDATE EMPLOYEE
SET SALARY = 67000.00
WHERE EMPLOYEE_ID = 2;

UPDATE EMPLOYEE
SET SALARY = 69000.00
WHERE EMPLOYEE_ID = 3;

UPDATE EMPLOYEE
SET SALARY = 75000.00
WHERE EMPLOYEE_ID = 4;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE
SET SALARY = 55000.00
WHERE EMPLOYEE_ID = 6;

UPDATE EMPLOYEE 
SET EMPLOYEE_ID = 5
WHERE EMPLOYEE_ID = 6;

-- NOTE DOWN ID WE ARE USING SERIAL WHEN WE EDIT SOME THINGS IN ROWS THE SERIAL NUMBER MAY BE DISTURB 









