CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    DEPARTMENT_ID INT,
    MANAGER_ID INT,
    SALARY NUMERIC(10,2)
);

INSERT INTO EMPLOYEE
(EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, MANAGER_ID, SALARY)
VALUES
(1, 'Arjun',    10, NULL, 80000),
(2, 'Rahul',    10, 1,    60000),
(3, 'Priya',    20, 4,    70000),
(4, 'Sneha',    20, NULL, 90000),
(5, 'Amit',     30, 6,    55000),
(6, 'Neha',     30, NULL, 75000),
(7, 'Rohan',    NULL, 1,  50000),
(8, 'Kiran',    40, NULL, 65000);



CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(50),
    LOCATION VARCHAR(50)
);


INSERT INTO DEPARTMENT
(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION)
VALUES
(10, 'IT',         'Pune'),
(20, 'HR',         'Mumbai'),
(30, 'Finance',    'Delhi'),
(40, 'Marketing',  'Bangalore'),
(50, 'Operations', 'Hyderabad');

SELECT * FROM EMPLOYEE , DEPARTMENT ;

SELECT E.FIRST_NAME , E.DEPARTMENT_ID , 
D.DEPARTMENT_ID , D.DEPARTMENT_NAME , D.LOCATION 
FROM EMPLOYEE E 
INNER JOIN 
DEPARTMENT D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID ;

SELECT E.FIRST_NAME , E.DEPARTMENT_ID , 
D.DEPARTMENT_ID , D.DEPARTMENT_NAME , D.LOCATION 
FROM EMPLOYEE E 
LEFT JOIN 
DEPARTMENT D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID ;

SELECT E.FIRST_NAME , E.DEPARTMENT_ID , 
D.DEPARTMENT_ID , D.DEPARTMENT_NAME , D.LOCATION 
FROM EMPLOYEE E 
RIGHT JOIN 
DEPARTMENT D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID ;


-- ADVANCE JOINS CROSS JOIN , FULL OUTER JOIN , SELF JOIN 
-- FULL OUTER JOIN SHOWS THE ALL RECORD FROM BOTH TABLES 
SELECT E.FIRST_NAME , E.DEPARTMENT_ID , 
D.DEPARTMENT_ID , D.DEPARTMENT_NAME , D.LOCATION 
FROM EMPLOYEE E 
FULL OUTER JOIN 
DEPARTMENT D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID ;


-- CROSS JOIN
-- RETRIVE ALL POSSIBLE COMBINATIONS 



SELECT E.FIRST_NAME , E.DEPARTMENT_ID , 
D.DEPARTMENT_ID , D.DEPARTMENT_NAME , D.LOCATION 
FROM EMPLOYEE E 
CROSS JOIN 
DEPARTMENT D ;




