-- LETS IMPORT THE CSV FILE INTO THE DATABASE 
-- FOR IMPORTING CSV FILE INTO THE DATABASE WE HAVE TO FIRST CRATE THE STRUCTURE OF THE TABLE
CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(100),
	DEPARTMENT VARCHAR(20),
	SALARY NUMERIC(10, 2),
	JOINING_DATE DATE,
	AGE INT
);

ALTER TABLE EMPLOYEE
ADD COLUMN EMAIL VARCHAR(100);

SELECT
	*
FROM
	EMPLOYEE;

--- IF IT IS NOT WORKING THEN IMPORT FROM THE IMPORT EXPORT OPTION 
-- ALSO CHANGE THE TYPE OF BACKSLASH TO FORWARD SLASH 
COPY EMPLOYEE (
	EMPLOYEE_ID,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	DEPARTMENT,
	SALARY,
	JOINING_DATE,
	AGE
)
FROM
	'C:\Users\HP\Downloads\employee_data.csv' DELIMITER ',' CSV HEADER;

-- FOR NOW I HAVE IMPOTED THE DATA WITH THE HELP OF IMPORT EXPORT OPTION 
-- LETS ADD BONUS ON THE SALARY 10 % 
SELECT
	FIRST_NAME,
	SALARY,
	(SALARY * 0.10) AS BONUS
FROM
	EMPLOYEE;

-- CALCULATE ANNUAL SALARY , INCREMANT SALARY AND NEW SALARY 
SELECT
	FIRST_NAME,
	LAST_NAME,
	SALARY,
	(SALARY * 12) AS ANNUAL_SALARY,
	(SALARY * 0.05) AS INCREMANT_SALARY,
	(SALARY + SALARY * 0.05) AS NEW_SALARY
FROM
	EMPLOYEE;

--  BETWEEN LIKE AND IN OPERATOR 
-- 1 BETWEEN OPERATOR 
SELECT
	*
FROM
	EMPLOYEE;

SELECT
	FIRST_NAME,
	SALARY
FROM
	EMPLOYEE
WHERE
	SALARY BETWEEN 50000 AND 60000;

--  LIKE OPERATOR 
SELECT
	LAST_NAME
FROM
	EMPLOYEE
WHERE
	LAST_NAME LIKE '%s';

-- IN OPERATOR 
SELECT
	DEPARTMENT,
	FIRST_NAME,
	EMPLOYEE_ID
FROM
	EMPLOYEE
WHERE
	DEPARTMENT IN ('IT', 'Operations');

-- IT WORKS WITH CASE SENSITIVITY
-- OTHER OPERATIONS 
-- 1 IS NULL 
SELECT
	*
FROM
	EMPLOYEE
WHERE
	SALARY IS NULL;

-- 2 ORDER BY 
SELECT
	*
FROM
	EMPLOYEE
ORDER BY
	SALARY DESC;

-- LIMIT  AND OFFSET  
SELECT
	*
FROM
	EMPLOYEE
ORDER BY
	SALARY DESC
LIMIT
	3
OFFSET
	1;

-- DISTINCT 
SELECT DISTINCT
	SALARY
FROM
	EMPLOYEE;

-- SET OPERATIONS 
SELECT
	*
FROM
	EMPLOYEE;

-- UNION IT WILL SHOW ONLY UNIQUE VALUES 
-- UNION ALL IT WILL SHOW DUPLICATE VALUES AS WEL 
-- INTERSECT ONLY SHOW COMMON VALUES 
-- EXCEPT SHOWS ONLY THOSE VALUE THAT ARE PRESENT IN FIRST TABLE BUT NOT IN THE SECOND TABLE 
--- NOW FUNCTIONS 
-- AGGREGATE FUNCTIONS 
SELECT
	COUNT(EMPLOYEE_ID)
FROM
	EMPLOYEE;

SELECT
	SUM(SALARY)
FROM
	EMPLOYEE;

SELECT
	AVG(SALARY)
FROM
	EMPLOYEE;

SELECT
	MAX(SALARY)
FROM
	EMPLOYEE;

SELECT
	MIN(SALARY)
FROM
	EMPLOYEE;

-- STRING FUNCTIONS IN SQL 
SELECT
	UPPER(FIRST_NAME)
FROM
	EMPLOYEE;

SELECT
	LOWER(LAST_NAME)
FROM
	EMPLOYEE;

SELECT
	LENGTH(FIRST_NAME)
FROM
	EMPLOYEE;

SELECT
	CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME
FROM
	EMPLOYEE;

SELECT
	FIRST_NAME,
	SUBSTRING(FIRST_NAME, 1, 3) AS SHORT_NAME
FROM
	EMPLOYEE;

SELECT
	TRIM(FIRST_NAME) AS CLEAN_NAME
FROM
	EMPLOYEE;

-- CASE 
-- CASE IS USED WITH THE CONDITIONS 
SELECT
	*
FROM
	EMPLOYEE;

SELECT
	SALARY,
	FIRST_NAME,
	CASE
		WHEN SALARY >= 60000 THEN 'GOOD'
		WHEN SALARY >= 40000
		AND SALARY <= 59999 THEN 'DISCENT SALARY'
		ELSE 'LOW SALARY'
	END AS SALARY_CATEGORY
FROM
	EMPLOYEE;

-- COALEASE FUNCTION 
-- IT WILL ADD THE VALUES FROM ANOTHER COLUMN 
ALTER TABLE EMPLOYEE
ADD COLUMN BONUS NUMERIC(10, 2);

SELECT
	*
FROM
	EMPLOYEE;

UPDATE EMPLOYEE
SET
	BONUS = SALARY * 0.09
WHERE
	DEPARTMENT NOT IN ('IT');

-- COALEASE 
SELECT
	FIRST_NAME,
	SALARY,
	BONUS,
	SALARY + COALESCE(BONUS, 0) AS FINAL_SALARY
FROM
	EMPLOYEE;

-- WINDOW FUNCTION IN SQL
-- IT IS USEFUL FOR RANKING THR ROWS 
-- 1ST ROW NUMBER ASSIGN UNIQUE NUMBER TO EACH ROW NO MATTER SAME OR DIFFERENT
-- IT WILL ASSIGN UNIQUE VALUE FOR EACH CATEGORY BASED 
-- IN THE RANK () I WILL ASSIGN RANK BUT IT WILL SKIP THE ROW IF THERE ISSAME VALUE MEANS EX IF WE HAVE 3 PRODUCT TWO PRODUCTS HAVE SAME PRICE THEN THE RANK GIVE SAME RANK FOR SAME VALUES AND GIVES 3 VALUE INSTEAD OF 2 IT WILL SKIP THE 2.
-- DENSE RANK() IT WILL GIVE SAME RANK FOR SAME BUT DONT SKIP FOR NEXT NUMBER IT WILL START FROM 2 .
-- LAG () GIVES THE VALUES FROM THE PREVIOUS ROW
-- LEAD () GIVES VALUE FROM THE NEXT ROW 
SELECT
	*
FROM
	EMPLOYEE
ORDER BY
	EMPLOYEE_ID DESC;

SELECT
    DEPARTMENT,
    FIRST_NAME,
    ROW_NUMBER() OVER (
        PARTITION BY DEPARTMENT
        ORDER BY SALARY DESC
    ) AS ROW_NUMBER
FROM EMPLOYEE;



SELECT
	DEPARTMENT,
	FIRST_NAME,
	SALARY,
	RANK() OVER (
		PARTITION BY
			DEPARTMENT
		ORDER BY
			SALARY DESC
	) AS ROW_RANKINGS
FROM
	EMPLOYEE;


SELECT
	DEPARTMENT,
	FIRST_NAME,
	SALARY,
	DENSE_RANK() OVER (
		PARTITION BY
			DEPARTMENT
		ORDER BY
			SALARY DESC
	) AS DENSE_RANKING
FROM
	EMPLOYEE;


	-- IN SHORT ROW NUMBER  = UNIQUE ASSIGN 
	-- RANK = ASSIGN RANK BUT IF SAME VALUE FOUND THEN SKIP  EX 1 1 3 SKIPS 2 
	-- DENSE RANK WORK PROPERLY IT WILL NOT SKIPS 1 1 2 3 LIKE THAT 


-- JOINS IN SQL 

	

	
